# name: panel
# channels:
#   - bioconda
#   - conda-forge
#   - r
#   - defaults
#   - pyviz
# dependencies:
#   - python=3
#   - hvplot
#   - jupyter
#   - notebook
#   - seaborn
#   - jupyter-panel-proxy
# prefix: /Users/Ruilin/opt/anaconda3/envs/panel
channels: - pyviz 
dependencies: - jupyter-panel-proxy

